### ISSUE TITLE
src 폴더가 없네요?

### ISSUE THREAD

**Issue by kismkof** [stepanowon/contactsvc#1]
vue.js quick start p.266 예제 10-02 번 윗줄에 보면
'미리 만들어놓은 contactsapp 프로젝트의 src 디렉터리 아래 ......' 라는 말이 나오는데 src 디렉터리가 없습니다. 추가해주세요

**Comment by stepanowon** [comment]
src 디렉토리는 vue app 프로젝트에 있는것을 말하는 겁니다. 
contactsvc 는 restful 방식의 백엔드서비스 프로젝트입니다. contactsvc 서비스를 구동해놓고 vue app  프로젝트인 contactsapp을 작성하시면됩니다. contactsapp이 contactsvc 서비스에 axios를 이용해 액세스합니다.
